site_name: treinamento-devops-epic
site_url: https://uiuqm.github.io/treinamento-devops-epic

nav:
  - Sobre: index.md
  - Apresentação e introdução: Apresentação - Introdução.md
  - Docker Images e Registry: Docker images e registry.md
  - Docker Networking: Docker network.md
  - Docker Compose: Docker Compose.md

theme: 
  name: material
  logo: ../img/epic_logo.svg